# Generated by Django 3.2.4 on 2021-06-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0002_brand_category_paymentmethod_product_sellproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
