# Generated by Django 3.2 on 2021-07-03 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0003_product_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellproducts',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='sellproducts',
            name='method',
        ),
        migrations.RemoveField(
            model_name='sellproducts',
            name='products',
        ),
        migrations.RemoveField(
            model_name='sellproducts',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='sellproducts',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='sellproducts',
            name='total',
        ),
        migrations.AddField(
            model_name='sellproducts',
            name='paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='sellproducts',
            name='paid_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SellItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_price', models.FloatField()),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='posApp.sellproducts')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='posApp.product')),
            ],
        ),
    ]
